_add_ function
VeraPrinsen/isomorphisms pull request #11
Opened 2019-02-27 15:44 UTC by mvandermade

initial commit

To test:

from supporting_components.graph import *

def create3(n: int):
    G = Graph(directed=False, n=n, simple=True)

    # Create a complete graph, connect one vertex to all other nodes
    # https://en.wikipedia.org/wiki/Complete_graph
    for i in range(0, len(G.vertices)):
        for j in range(i+1, len(G.vertices)):
            G+= Edge(G.vertices[i], G.vertices[j])

    return G

print('adding 2 graphs')
g1 = create3(2)
g2 = create3(3)

print('before:')
print(g1)
print(g2)

print('after')
nG = g1 + g2
print(nG)

2019-02-27 15:50 UTC, JKleinRot requested changes
Een klein dingetje

2019-02-27 15:50 UTC, JKleinRot commented on supporting_components/graph.py
> +        for v_before_union in self.edges + other.edges:
Ik zou deze dan `e_before_union` noemen

2019-02-28 09:19 UTC, VeraPrinsen approved these changes
Goed!

2019-02-28 15:02 UTC, JKleinRot approved these changes

2019-03-01 07:49 UTC, merged