Create tests/decide_gi.py test method for is_balanced_or_is_bijected fixes #31
VeraPrinsen/isomorphisms pull request #35
Opened 2019-03-11 10:53 UTC by mvandermade

Tests the function is_balanced_or_bijected.

The test structure is based on the tests/graph.py file.

Uses a dictionary to store the results from canvas.
Runs the test for each combination of graphs within a .grl file.
If the test fails for one graph combination debug information is printed.

Added a integer of the total number of expected test runs.
This number is displayed in the test summary.

2019-03-11 11:07 UTC, VeraPrinsen requested changes

2019-03-11 11:07 UTC, VeraPrinsen commented on tests/decide_gi.py
> +    with open(filename) as f:
In input_output/file_output (wat file_io moet heten besef ik me nu), zit een methode load_graph_list, waarin dit is geimplementeerd. Dan krijg je ook gelijk de L[0], zodat je dat hier nergens meer hoeft te doen.

2019-03-11 11:07 UTC, VeraPrinsen commented on tests/decide_gi.py
> +                    print("Is calculated is_balanced_or_bijected correctly: " + str(is_balanced_or_bijected_test_result))
Je kunt hier om de gefaalde tests te benadrukken de fail() methode uit sys_output gebruiken die in input_output staat.

2019-03-11 11:07 UTC, VeraPrinsen commented on tests/decide_gi.py
> +        print('DEBUG...')
Als dit voorkomt, wordt dit geprint voordat je weet over welke file het gaat.

2019-03-11 11:07 UTC, VeraPrinsen commented on tests/decide_gi.py
> +expected_results['colorref_smallexample_2_49'] = {0:
Vind de indentatie hier niet zo leesbaar, maar is meer een style dingetje

2019-03-12 08:59 UTC, JKleinRot requested changes
Paar kleine dingen

2019-03-12 08:59 UTC, JKleinRot commented on tests/decide_gi.py
> +def test_balanced_or_bijected(graph: 'Graph', is_balanced: bool, is_bijected: bool):
Volgens mij moet de typing van een boolean ook met hoofdletter en '': `is_balanced: 'Bool'`

2019-03-12 08:59 UTC, JKleinRot commented on tests/decide_gi.py
> +    Tests the is_balanced_or_bijected method of decide_gi.py agains expected answers for is_balanced and is_bijected
against

2019-03-12 08:59 UTC, JKleinRot commented on tests/decide_gi.py
> +total_tests = 22
Dit vraagt wel om handmatig aanpassen van het aantal testen dat gerund wordt. Als je er een file bij toevoegt en je past dit niet aan, dan faalt de test als nog. Mag om mij wel blijven staan, maar volgens mij biedt het niet wat extra's in de test.

2019-03-12 09:19 UTC, VeraPrinsen submitted a review, later dismissed

2019-03-12 09:29 UTC, mvandermade commented on tests/decide_gi.py
> +def test_balanced_or_bijected(graph: 'Graph', is_balanced: bool, is_bijected: bool):
Beide zijn goed volgens de pydocs, voor consistentie heb ik het aangepast naar 'Bool'.

https://docs.python.org/3/library/typing.html

2019-03-13 13:02 UTC, JKleinRot approved these changes

2019-03-13 13:02 UTC, merged