Separate test for general isomorphism problem
VeraPrinsen/isomorphisms pull request #54
Opened 2019-03-14 15:13 UTC by VeraPrinsen

Ik heb in deze PR de test voor branching aangepast zodat deze alleen de algorithmen gebruikt in de algotithms/branching.py module. En daarnaast heb ik dus een algemene test aangemaakt voor het algemene Graph Isomorphism probleem. 

In beide tests heb ik toegevoegd dat resultaten kunnen worden opgeslagen in een csv file.

Omdat de twin removal nog niet goed werkt, heb ik in het algemene algoritme deze nog niet toegevoegd, dat moet dan maar getest worden in issue #50.

2019-03-14 15:22 UTC, JKleinRot requested changes
Iets kleins over de excel kolomnamen

2019-03-14 15:22 UTC, JKleinRot commented on tests/branching.py
> +    csv_column_names = ['file', 'graph1', 'graph2', 'are_isomorph processing time (s)', 'result', 'amount_of_isomorphisms processing time (s)', 'result']
Misschien zou ik hier 'passed' van maken ipv 'result'. Zoals ik het begrijp zet je in die kolom of de test geslaagd is, en zo zou je het ook kunnen lezen alsof de grafen isomorph zijn.

2019-03-14 15:22 UTC, JKleinRot commented on tests/isomorphism_problem.py
> +    csv_column_names = ['file', 'graph1', 'graph2', 'are_isomorph processing time (s)', 'result', 'amount_of_isomorphisms processing time (s)', 'result']
Hier dezelfde opmerking als bij de andere test.

2019-03-14 15:46 UTC, mvandermade submitted a review, later dismissed

2019-03-14 15:46 UTC, mvandermade commented on tests/isomorphism_problem.py
> +# todo: Add more test files? How can we do this easily so we can do it the 10th of April fast?
misschien is het handig om een "test graph" Class te maken ?

2019-03-14 15:46 UTC, mvandermade commented on tests/isomorphism_problem.py
> +trees90 = True
```suggestion
trees90 = False
```

2019-03-14 15:46 UTC, mvandermade commented on tests/isomorphism_problem.py
> +torus24 = True
```suggestion
torus24 = False
```

2019-03-15 08:11 UTC, JKleinRot approved these changes

2019-03-15 08:17 UTC, merged